spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/employeedb
  username: postgres
  password: 1234

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  properties.hibernate.format_sql: true